### ISSUE TITLE
Cannot open <openface_nn4.small2.v1.t7> in mode r  in function 'THDiskFile_new'

### ISSUE THREAD

**Issue by Prashant-mahajan** [Ravi-Singh88/Face-Recognition-OpenCV-Facenet#1]
Hi, 
I am getting the following error whenever I try to run the first command i.e. 
`python extract_embeddings.py --dataset dataset --embeddings output/embeddings.pickle --detector face_detection_model --embedding-model openface_nn4.small2.v1.t7`

Error: 
`Loading Caffe based face detector to localize faces in an image
Loading Openface imlementation of Facenet model
Traceback (most recent call last):
  File "extract_embeddings.py", line 34, in <module>
    embedder = cv2.dnn.readNetFromTorch(args["embedding_model"])
cv2.error: OpenCV(3.4.5) /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/torch/THDiskFile.cpp:496: error: (-2:Unspecified error) cannot open <openface_nn4.small2.v1.t7> in mode r  in function 'THDiskFile_new'`

Installed the necessary libraries as well as followed the directory structure mentioned in the README file. Here's how directory looks like - 

> |____extract_embeddings.py
|____video
| |____input.mp4
|____train_model.py
|____face_detection_model
| |____deploy.prototxt
| |____res10_300x300_ssd_iter_140000.caffemodel
|____dataset
| |____Rajnikant
| | |____iu.jpeg
| | |____rajnikant.jpeg
| | |____iu-3.jpeg
| | |____iu-2.jpeg
| | |____iu-5.jpeg
| | |____iu-4.jpeg
| |____Amy
| | |____iu.jpeg
| | |____iu-3.jpeg
| | |____iu-2.jpeg
| | |____iu-5.jpeg
| | |____iu-4.jpeg
|____output
|____recognize_video_file.py
|____README.md

Any help would be appreciated. Thank you!

**Comment by Ravi-Singh88** [comment]
Let me have a look. I think I got the issue. Will respond by today evening

**Comment by Ravi-Singh88** [comment]
Hey Prashant,

The open face model file is more than 25MB and hence it didn't get uploaded. 

Download the openface nn4.small2.v1.t7 model from the open face portal link https://storage.cmusatyalab.org/openface-models/nn4.small2.v1.t7

I have also edited the readme file

**Comment by dronesmedellin** [comment]
Thanks, it worked for me, but I had to change the name in :
FROM: `embedder = cv2.dnn.readNetFromTorch('openface.nn4.small2.v1.t7')`
TO:  `embedder = cv2.dnn.readNetFromTorch('nn4.small2.v1.t7')`
